api.baseUrl=http://localhost:4111
apiVersion=/api/v1/

admin.username=admin
admin.password=admin

ui.remote=http://localhost:4444/wd/hub
ui.baseUrl=http://192.168.1.100:3000
ui.browser=chrome
ui.browserSize=1920x1080
ui.timeout=15000