api.baseUrl=http://localhost:4111
apiVersion=/api/v1/
api.version=with_database_with_fix
#with_validation_fix
#with_database_with_fix

admin.username=admin
admin.password=admin

ui.remote=http://localhost:4444/wd/hub
ui.baseUrl=http://192.168.1.100:3000
ui.browser=chrome
ui.browserSize=1920x1080
ui.timeout=15000

# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers

# Fraud service configuration (for testing with WireMock)
fraud.service.url=http://localhost:8080